version: "3.9"
services:
  stkweb:
    image: sontek/stkweb

  stkapi:
    image: sontek/stkapi

  stknginx:
    image: sontek/stknginx
    ports:
      - "80:80"
    environment:
      - STK_API_HOST=stkapi
      - STK_WEB_HOST=stkweb
    depends_on:
      - stkweb
      - stkapi
